version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3000
      - SUPABASE_PROJECT_URL=${SUPABASE_PROJECT_URL}
      - SUPABASE_API_KEY=${SUPABASE_API_KEY}
      - SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}
      - SUPABASE_REALTIME_URL=${SUPABASE_REALTIME_URL}
      - SUPABASE_REALTIME_KEY=${SUPABASE_REALTIME_KEY}
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start

volumes:
  # Remove Redis volume
  # redis_data: 