version: '3.8'

services:
  base:
    build:
      context: ./chatwoot
      dockerfile: Dockerfile
    environment:
      - RAILS_ENV=production
      - NODE_ENV=production
      - SUPABASE_PROJECT_URL=${SUPABASE_PROJECT_URL}
      - SUPABASE_API_KEY=${SUPABASE_API_KEY}
      - SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}
      - SUPABASE_REALTIME_URL=${SUPABASE_REALTIME_URL}
      - SUPABASE_REALTIME_KEY=${SUPABASE_REALTIME_KEY}
    volumes:
      - ./chatwoot:/app
    ports:
      - "3000:3000"
    command: ./bin/docker-entrypoint.sh

volumes:
  # Remove Redis volume
  # redis_data: 